In [23]:
import h5py
import numpy as np
import matplotlib.pyplot as plt

In [25]:
g = h5py.File("../data/pairs/Illustris_z0-io.hdf5","r")

In [31]:
8*6047594*18*4/1e9

3.483414144

18

In [13]:
f = h5py.File("../data/subhalos/Illustris_135.hdf5","r")

In [20]:
len(f['hydro']['dwarf'])

<KeysViewHDF5 ['Group ID', 'Group Mass', 'Group Radius', 'Nsubs', 'Subhalo ID', 'Subhalo Mass', 'Subhalo Max Mass', 'Subhalo Max Mass Snap', 'Subhalo Med Stellar Mass', 'Subhalo Pos', 'Subhalo Stellar Masses', 'Subhalo Vel']>

In [22]:
np.array(f['hydro']['dwarf']['Nsubs'])

array([87, 87, 87, ...,  4,  3,  3], dtype=int32)

In [3]:
f.keys()

<KeysViewHDF5 ['hydro']>

In [8]:
from utils.get_groups import GetGroups
from utils.read_group_cats import ReadCats


In [4]:
TNGtest = GetGroups(99,"TNG","dark")
TNGtestH = GetGroups(99,"TNG","hydro")

print(TNGtest.inds[0:10])
print(TNGtestH.inds[0:10])

NameError: name 'GetGroups' is not defined

In [3]:
TNGtest = GetGroups(90,"TNG","dark")
TNGtestH = GetGroups(90,"TNG","hydro")

print(TNGtest.inds[0:10])
print(TNGtestH.inds[0:10])

[     0  19021  37280  52178  65172  75430  84922  95250 103297 113891]
[    0 13164 26358 36942 46165 52854 60190 67567 73042 80760]


In [4]:
TNGtest = GetGroups(89,"TNG","dark")
TNGtestH = GetGroups(89,"TNG","hydro")

print(TNGtest.inds[0:10])
print(TNGtestH.inds[0:10])

[     0  18934  37119  51717  65177  74653  84720  94849 105347 114209]
[    0 13186 26369 36697 43319 50612 57182 63263 70914 77282]


In [5]:
darks = ReadCats(snapshot=89, 
            sim="TNG", 
            physics="dark"
            )
hydros = ReadCats(snapshot=89, 
            sim="TNG", 
            physics="hydro"
            )

In [6]:
darks.submass

array([2.17676035e+04, 2.89894653e+03, 4.86613159e+02, ...,
       1.91990044e-02, 1.91990044e-02, 1.79990660e-02])

In [7]:
hydros.submass

array([2.41007285e+04, 6.23312134e+02, 2.74355865e+02, ...,
       1.41560799e-02, 1.56728029e-02, 1.56728029e-02])

In [ ]:
darks = ReadCats(snapshot=71, 
            sim="TNG", 
            physics="dark"
            )
hydros = ReadCats(snapshot=71, 
            sim="TNG", 
            physics="hydro"
            )